# Generated by Django 3.2.23 on 2024-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción de la organización', max_length=300, null=True),
        ),
    ]
