# Generated by Django 3.2.23 on 2024-12-08 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_auto_20241207_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['organization', 'ciudad'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterField(
            model_name='direction',
            name='calle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direction',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direction',
            name='codigo_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='direction',
            name='colonia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direction',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direction',
            name='numero_exterior',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='direction',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(help_text='Nombre de la planta', max_length=100, unique=True)),
                ('description', models.CharField(help_text='Descripción de la planta', max_length=200)),
                ('address', models.ForeignKey(help_text='Dirección de la planta', on_delete=django.db.models.deletion.CASCADE, to='company.direction')),
                ('organization', models.ForeignKey(help_text='Organización a la que pertenece', on_delete=django.db.models.deletion.CASCADE, to='company.organization')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['name'],
            },
        ),
    ]
